Repository YACS-RCOS/yacs.n, pull requests merged in 2020-03, with the labels that each got.

#38 Export Schedule to ICS
  src/yacs-web/.env.development
  src/yacs-web/.env.production
  src/yacs-web/package.json
  src/yacs-web/public/ics.min.js
  src/yacs-web/public/index.html
  src/yacs-web/src/components/Schedule.vue
  src/yacs-web/src/pages/Main.vue
  src/yacs-web/src/services/ScheduleService.js
  src/yacs-web/vue.config.js
Labels: enhancement

#57 Fixed 12:00 bug
  rpi-data/fall-2020.csv
  rpi-data/modules/rpi-parse.py
  rpi-data/summer-2020.csv
Labels: bug

#62 Cross plat start script
  .env
  .gitignore
  package.json
Labels: enhancement

#51 Add SubsemesterScheduler, component reorganization, Prettier code style, add jsdocs
  src/app.py
  src/requirements.txt
  src/yacs-web/.eslintrc.js
  src/yacs-web/.gitignore
  src/yacs-web/.prettierrc
  src/yacs-web/README.md
  src/yacs-web/babel.config.js
  src/yacs-web/jsconfig.json
  src/yacs-web/jsdoc.config.json
  src/yacs-web/package-lock.json
  src/yacs-web/package.json
  src/yacs-web/src/App.vue
  src/yacs-web/src/components/CourseList.vue
  src/yacs-web/src/components/Header.vue
  src/yacs-web/src/components/Schedule.vue
  src/yacs-web/src/components/ScheduleEvent.vue
  src/yacs-web/src/components/SelectedCourses.vue
  src/yacs-web/src/controllers/Schedule.js
  src/yacs-web/src/controllers/SubSemesterScheduler.js
  src/yacs-web/src/main.js
  src/yacs-web/src/mixins/NotificationsMixin.js
  src/yacs-web/src/pages/Admin.vue
  src/yacs-web/src/pages/Main.vue
  src/yacs-web/src/routes.js
  src/yacs-web/src/services/AdminService.js
  src/yacs-web/src/services/ColorService.js
  src/yacs-web/src/services/ScheduleService.js
  src/yacs-web/src/services/YacsService.js
  src/yacs-web/src/typedef.js
  src/yacs-web/src/utils.js
  src/yacs-web/vue.config.js
Labels: documentation, enhancement, in progress

#66 Add toggle of side panel between SelectedCourses and CourseList
  src/public/.DS_Store
  src/yacs-web/src/App.vue
  src/yacs-web/src/components/CourseList.vue
  src/yacs-web/src/components/CourseListing.vue
  src/yacs-web/src/components/Header.vue
  src/yacs-web/src/components/Schedule.vue
  src/yacs-web/src/components/ScheduleEvent.vue
  src/yacs-web/src/components/SelectedCourses.vue
  src/yacs-web/src/controllers/Schedule.js
  src/yacs-web/src/pages/Main.vue
  src/yacs-web/src/services/YacsService.js
Labels: enhancement

#67 Add crn check between courses and sections to fix duplicate sections
  src/db/classinfo.py
Labels: bug

#65 Map date range to name.
  .env
  package-lock.json
  src/app.py
  src/data/build.sh
  src/data/clear.sh
  src/data/schema/semester_date_range.sql
  src/db/classinfo.py
  src/db/connection.py
  src/db/semester_date_mapping.py
  src/yacs-web/package.json
  src/yacs-web/public/ics.min.js
  src/yacs-web/src/components/EditSemesterDateNameBinding.vue
  src/yacs-web/src/pages/Admin.vue
  src/yacs-web/src/pages/Main.vue
  src/yacs-web/src/pages/MapDates.vue
  src/yacs-web/src/pages/UploadCsv.vue
  src/yacs-web/src/routes.js
  src/yacs-web/src/services/AdminService.js
  src/yacs-web/src/services/YacsService.js
  src/yacs-web/src/typedef.js
  src/yacs-web/src/utils.js
Labels: enhancement
