Repository YACS-RCOS/yacs.n, pull requests merged in 2020-04, with the labels that each got.

#76 User System
  src/API.md
  src/api/app.py
  src/api/common.py
  src/api/controller/session.py
  src/api/controller/user.py
  src/api/controller/userevent.py
  src/api/db/connection.py
  src/api/db/model.py
  src/api/db/session.py
  src/api/db/user.py
  src/api/db/userevent.py
  src/api/view/message.py
  src/data/schema/user.sql
  src/data/schema/user_event.sql
  src/data/schema/user_session.sql
  src/data/user.sh
  src/web/package-lock.json
  src/web/package.json
  src/web/src/components/Header.vue
  src/web/src/main.js
  src/web/src/services/UserService.js
  tests/api/db/test_classinfo.py
Labels: in progress

#64 Semester switching enabled
  package.json
  rpi-data/get-spring-2020.sh
  rpi-data/spring-2020.csv
  src/api/app.py
  src/api/db/admin.py
  src/api/db/classinfo.py
  src/api/db/connection.py
  src/data/build.sh
  src/data/clear.sh
  src/data/schema/admin_setting.sql
  src/db/admin.py
  src/web/package-lock.json
  src/web/src/components/CourseList.vue
  src/web/src/components/Footer.vue
  src/web/src/components/Header.vue
  src/web/src/pages/Admin.vue
  src/web/src/pages/Main.vue
  src/web/src/pages/SetDefault.vue
  src/web/src/services/AdminService.js
  src/web/src/services/YacsService.js
  src/yacs-web/src/pages/Admin.vue
Labels: Priority 1

#91 Minor UI fixes
  conftest.py
  src/api/db/admin.py
  src/api/db/connection.py
  src/web/src/components/CourseList.vue
  src/web/src/components/Footer.vue
  src/web/src/components/Header.vue
  src/web/src/pages/Admin.vue
  src/web/src/pages/Main.vue
  src/web/src/pages/SetDefault.vue
  src/web/src/pages/UploadCsv.vue
  src/web/src/services/AdminService.js
  src/web/src/services/YacsService.js
  tests/api/db/test_admin.py
  tests/api/db/test_classinfo.py
Labels: enhancement

#94 Scheduling — Display full course details in Schedule View
  src/web/src/components/Schedule.vue
  src/web/src/components/ScheduleEvent.vue
  src/web/src/controllers/Schedule.js
  src/web/src/controllers/SubSemesterScheduler.js
  src/web/src/pages/Main.vue
Labels: Priority 2, in progress

#114 Pull Request Template
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Labels: Review Ready!

#116 Fix semester options not being updated in course list
  src/web/src/components/CourseList.vue
  src/web/src/pages/Main.vue
  src/web/src/services/YacsService.js
Labels: bug

#109 Save selected courses
  conftest.py
  scripts/dev-build.sh
  scripts/dev-start.sh
  scripts/dev-stop.sh
  src/api/app.py
  src/api/db/student_course_selection.py
  src/data/build.sh
  src/data/schema/07_user.sql
  src/data/schema/08_user_session.sql
  src/data/schema/09_user_event.sql
  src/data/schema/10_student_course_selection.sql
  src/data/user.sh
  src/web/src/components/CourseList.vue
  src/web/src/components/Header.vue
  src/web/src/pages/Main.vue
  src/web/src/services/YacsService.js
  tests/api/db/test_saving.py
Labels: Priority 1, Review Ready!

#118 hotfix: change default admin password
  docker-compose.production.yml
Labels: Hotfix

#120 Added userID cookie storage back
  src/web/src/components/Header.vue
  src/web/src/components/SignUp.vue
Labels: bug

#132 Add first course section when adding course
  src/web/src/pages/Main.vue
Labels: Review Ready!

#131 Fixing UX bugs from #126
  src/web/src/components/CourseListing.vue
  src/web/src/components/Footer.vue
  src/web/src/components/SelectedCourses.vue
  src/web/src/pages/Main.vue
Labels: Review Ready!

#140 Add back button functionality to course listing
  src/web/src/components/CourseListing.vue
Labels: Review Ready!, bug

#138 Add course information to CourseList
  src/web/src/components/CourseList.vue
  src/web/src/components/CourseListing.vue
  src/web/src/components/SelectedCourses.vue
Labels: Review Ready!, in progress

#141 Add loading spinner to course list
  src/web/public/index.html
  src/web/src/pages/Main.vue
Labels: Review Ready!

#133 Fix ICS export & update metadata
  src/web/public/ics.min.js
  src/web/src/main.js
  src/web/src/pages/Main.vue
  src/web/src/utils.js
Labels: in progress

#147 Change Other Semesters to more logical style
  src/web/src/components/Footer.vue
Labels: Feature Request, Review Ready!, v0 responsive
