Repository YACS-RCOS/yacs.n, pull requests merged in 2020-10, with the labels that each got.

#218 allowing multiple ssh keys for feature envs
  .github/workflows/pr-cd.yaml
  ops/provision.js
Labels: DevEx

#232 Changed YACS to direct to CourseScheduler by updating Header.vue
  src/web/src/components/Header.vue
Labels: hacktoberfest-accepted

#258 Fixed display name to be course_name from full_name
  src/web/src/components/CourseListing.vue
Labels: Review Ready!, bug
