Repository YACS-RCOS/yacs.n, pull requests merged in 2021-11, with the labels that each got.

#493 Resolved Default Semester Bug
  src/api/app.py
  src/api/db/admin.py
Labels: Review Ready!, Approved!

#506 All possible schedules
  src/web/src/components/CourseList.vue
  src/web/src/components/CourseListing.vue
  src/web/src/components/Schedule.vue
  src/web/src/components/SelectedCourses.vue
  src/web/src/controllers/Schedule.js
  src/web/src/controllers/SelectedIndexCookie.js
  src/web/src/controllers/SubSemesterScheduler.js
  src/web/src/doc/scheduler.md
  src/web/src/pages/NewCourseScheduler.vue
  src/web/src/routes.js
  src/web/src/services/ColorService.js
  src/web/src/services/YacsService.js
  src/web/src/utils.js
Labels: Priority 1, Review Ready!

#481 More Info in Schedule Events
  src/api/db/courses.py
  src/api/migrations/versions/2021-09-25_add_session_type_and_instructor.py
  src/api/tables/course_session.py
  src/web/src/assets/dark.scss
  src/web/src/components/Schedule.vue
  src/web/src/components/ScheduleEvent.vue
  src/web/src/services/ColorService.js
  src/web/src/store/index.js
  src/web/src/typedef.js
Labels: Review Ready!
